import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const roboto = Roboto({
   weight: '400',
   subsets: ["latin"] 
  
  });

export const metadata = {
  title: "Lama",
  description: "Generated by create next app",
};

export default function RootLayout({ children , params }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar params={params}/>
        {children}
        </body>
    </html>
  );
}
